apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-website
  labels:
    app: nginx-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-website
  template:
    metadata:
      labels:
        app: nginx-website
    spec:
      containers:
      - name: nginx
        image: "acrsd6027dev.azurecr.io/nginx-website:latest"
        ports:
        - containerPort: 80
